name: CD â€“ Deploy to Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production Kubernetes
    runs-on: self-hosted  
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull Docker Image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/weather-ml-app:latest

      - name: Ensure Minikube is Running
        run: |
          minikube status || minikube start --force

      - name: Set kubectl context
        run: |
          kubectl config use-context minikube

      - name: Apply Deployment
        run: |
          kubectl apply -f k8s/deployment.yaml

      - name: Apply Service
        run: |
          kubectl apply -f k8s/service.yaml

      - name: Set new image version for rolling update
        run: |
          kubectl set image deployment/weather-ml-app weather-ml-app=${{ secrets.DOCKERHUB_USERNAME }}/weather-ml-app:latest

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/weather-ml-app --timeout=120s

      - name: Get service info
        run: |
          echo "Minikube IP:"
          minikube ip
          echo "K8s services:"
          kubectl get svc -o wide
